Repository githubschool/disney-plus, pull requests merged in 2019-11, with the labels that each got.

#24 ash's caption
  _posts/0000-01-03-ashvenkatraman.md
Labels: duplicate, help wanted

#26 beardofedu's caption
  _posts/0000-01-17-beardofedu.md
Labels: enhancement

#34 SLEEP1NG's caption
  _posts/0000-01-06-SLEEP1NG.md
Labels: documentation

#27 princejacobkuruvilla's caption
  _posts/0000-01-07-princejacobkuruvilla.md
Labels: enhancement

#28 marcw1000 caption update
  _posts/0000-01-13-marcW1000.md
Labels: enhancement
